### ISSUE TITLE
Add all contributors

### ISSUE THREAD

**Issue by arecvlohe** [nativesintech/muscogee-creek-dictionary-admin#1]

**Comment by arecvlohe** [comment]
@all-contributors please add @arecvlohe for code,code,infra

**Comment by arecvlohe** [comment]
@all-contributors add @arecvlohe code,doc,infra

**Comment by arecvlohe** [comment]
@all-contributors add @arecvlohe for code,doc,infra

**Comment by arecvlohe** [comment]
@all-contributors add @arecvlohe for code, doc, infra

**Comment by microfauna** [comment]
Woohoo! 🎉
